version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: dev-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: exchange_db
      MYSQL_USER: exchange
      MYSQL_PASSWORD: ex@1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: dev-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

networks:
  backend:

volumes:
  redis-data:
