spring:
  application:
    name: backend

  config:
    import: optional:application-secret.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
